export const LOGIN_TEXT = "Log In";
export const WELCOME_BACK_TEXT = "Welcome Back!";

export const FORM_LABELS = {
    PATIENT_NAME: "Patient name",
    GENDER: "Gender",
    AGE: "Age",
    PHONE: "Phone",
    EMAIL: "Email",
    REFERED_DOCTOR: "Referred doctor",
    OTCRX: "OTC / Rx",
    MEDICINE_NAME: "Medicine Name",
    PHARMACOLOGICAL_NAME: "Pharmacological Name",
    BRAND_NAME: "Brand Name",
    QUANTITY: "Unity / Strips",
    MRP: "MRP",
    TOTAL: "Total",
    DISCOUNT: "Discount %",
    BATCH_NO: "Batch No",
    HSN_CODE: "HSN Code",
    PRICE: "Price",
    AMOUNT: "Amount",
    PAYMENT_MODE: "Payment mode",
    GST: "GST Total %",
    NET_PRICE: "Net price",
    ROUND_OFF: "Round Off",
    BILL_AMOUNT: "Bill Amount",
    PAID_AMOUNT: "Paid Amount",
    VENDOR_NAME: "Vendor Name",
    DOSE: "Dose",
    FORM: "Form",
    PURCHASE_REQUISITION_ID: "Purchase Requisition Id",
    QUOTATION_ID: "Quotation Id",
    PTR: "PTR",
    PTS: "PTS",
    ADDRESS: "Address",
    INVOICE_NUMBER:"Invoice Number",
    PO_NUMBER:"PO Number",
    INVOICE_DATE:"Invoice Date",
    EXPIRY:"Expiry",
    UNITS_STRIPS:"Units / Strips",
    NO_OF_STRIPS:"No of Strips",
    FREE_STRIPS:"Free Strips",
    MRP_PER_STRIP:"MRP Per Strip",
    PRICE_PER_STRIP:"Price Per Strip",
    ADD_REMARKS:"Add Remarks",
}



