import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';
import reportWebVitals from './reportWebVitals';
// import { Provider } from 'react-redux';
// import store from './shared/services/redux/store';
const container = document.getElementById('root');
const root = createRoot(container); 
root.render(<App />);
// root.render( <Provider store={store}><App /></Provider> );
reportWebVitals();